- name: homebrew | nginx
  homebrew:
    name: nginx
    state: present

- name: Copy nginx.conf
  copy:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
  notify:
  - restart nginx

- name: homebrew | upgrade all
  homebrew:
    upgrade_all: true