- hosts: localhost
  tasks:
    - include_role: 
        name: homebrew_cask
    - include_role: 
        name: homebrew
    - include_role: 
        name: git
    - include_role: 
        name: mac-settings
    - include_role: 
        name: zsh
    - include_role: 
        name: terminal-prompt
    - include_role: 
        name: terminal-themes
    - include_role: 
        name: zsh-plugins