- hosts: localhost
  tasks:
    - include_role: 
        name: git
    - include_role: 
        name: mac-settings
    - include_role: 
        name: homebrew_cask
    - include_role: 
        name: homebrew
    - include_role: 
        name: config
    - include_role:
        name: tmux
    - include_role: 
        name: zsh
      tags:
        - zsh