# Alacritty Configuration Fil# Alacritty Configuration Fil# Alacritty Configuration Fil# Alacritty Configuration File
# Docs: https://github.com/alacritty/alacritty

# Font configuration
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

# Environment variables
[env]
TERM = "xterm-256color"

# Import the Catppuccin theme
[general]
import = [
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/catppuccin-mocha.toml"
]
#
# Cursor style
[cursor]
style = "Beam"

# Scrolling
[scrolling]
history = 10000
multiplier = 3

# Window configuration
[window]
dynamic_title = true
decorations = "none"
#opacity = 0.9
dimensions = { columns = 80, lines = 24 }

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "(/opt/homebrew/bin/tmux attach-session -t default || /opt/homebrew/bin/tmux new-session -s default) && exec zsh"]