- name: zsh | zsh
  homebrew:
    name: zsh
    state: present
  tags:
    - zsh

- name: zsh | Symlink .zshrc
  file:
    src: "{{ playbook_dir }}/roles/zsh/files/.zshrc"
    dest: ~/.zshrc
    state: link
  tags:
    - zsh